# Template Dockerfile for All Sanic Based Testing Apps
ARG DOCKER_REGISTRY
ARG BUILD_TAG
FROM ${DOCKER_REGISTRY}/sanic:${BUILD_TAG}-test

# Add everything of the app
COPY blueprint.py orm.py requirements.txt requirements-test.txt ./
COPY tests tests
COPY views views

# Install dependencies, no cleanup
RUN pip install -r requirements.txt -r requirements-test.txt