sudo: required
language: python
dist: xenial
services:
  - docker
notifications:
  email:
    on_success: always
    on_failure: always
branches:
  only:
    - master

env:
  - HELM_RELEASE_NAME=release-ci
before_install:
  - sudo apt-get install -y socat
script:
  - make ci
after_success:
  - docker images
