sudo: required
dist: xenial

services:
  - docker
notifications:
  email:
    on_success: always
    on_failure: always
branches:
  only:
    - master
script:
  - make ci
after_success:
  - docker images
