dependencies:
- name: postgresql
  version: 0.15.0
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: postgresTesting
  condition: testing
- name: gcloud-sqlproxy
  version: 0.4.0
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: postgres
  condition: notTesting
- name: nginx-ingress
  version: 0.23.0
  repository: https://kubernetes-charts.storage.googleapis.com
- name: external-dns
  version: 0.7.1
  repository: https://kubernetes-charts.storage.googleapis.com
  condition: notTesting
  alias: externalDNS
- name: cert-manager
  version: v0.4.0
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: certManager