dependencies:
- name: postgresql
  version: 0.15.0
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: db-postgres-test
  condition: testing
- name: gcloud-sqlproxy
  version: 0.4.0
  repository: https://kubernetes-charts.storage.googleapis.com
  alias: db-postgres
  condition: not-testing
