# with testing=true:
#   - deploy test image
#   - image includes testing frameworks (ipdb, pytest)
#   - image have abality to run test cases
#   - deploy & connect to a test db
# with testing=false:
#   - deploy prod image
#   - test cases are removed from images
#   - connect to prod db
testing: false
notTesting: true   # workaround the issue that currently no way to have logic not in requirements.yaml conditions

# Some values require override from main Makefile with values specified through Environment Variables.
# The name of the variables are documented as:  ENV: <Variable Name>

dockerRegistry: library   # docker registry path for image pulling.  ENV: DOCKER_REGISTRY
buildTag: latest             # the build tag to use.   ENV: BUILD_TAG
tlsSecret: tls-secret     # secret storing the tls certs for ingress. ENV: PROD_K8S_SECRET_TLS
databaseSecret: &databaseSecret database-secret  # secret for connecting to Cloud SQL database. ENV: PROD_K8S_SECRET_DATABASE
staticIP: static-ip       # static-ip name (in gce) for ingress. ENV: PROD_GCP_STATIC_IP

postgres:
  existingSecret: *databaseSecret   # ENV: PROD_K8S_SECRET_DATABASE
  existingSecretKey: instance-credential
  cloudsql:
    instances:
    - project: project    # ENV: PROD_GCP_DB_PROJECT
      region: retion      # ENV: PROD_GCP_DB_REGION
      instance: instance  # ENV: PROD_GCP_DB_INSTANCE
      port: 5432

postgresTesting:
  nameOverride: postgres-testing
  postgresUser: postgres
  postgresPassword: postgres
  postgresConfig:
    logConnections: yes
    logHostname: yes
    logStatement: all
  persistence:
    enabled: false    # ENV: DEV_PERSIST_DB
  service:
    port: 5432

appConfigs:
  dns:
    type: service
    pullPolicy: IfNotPresent
    replicas: 3
    serviceType: ClusterIP
    tcpPorts: [80]
    udpPorts: []
    ingress:
    - path: "/ddns/"
    envPrefix: "SANIC_"
    envDatabase: true
    env:
      DDNS_ZONE: local  # ENV: DDNS_ZONE
    env_raw:
      GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google/key.json
    mountSecrets:
    - name: dns-secret
      path: /var/secrets/google/
  misc:
    type: service
    pullPolicy: IfNotPresent
    replicas: 3
    serviceType: ClusterIP
    tcpPorts: [80]
    udpPorts: []
    ingress:
    - path: "/generate_204"
      port: 80 # if absent the first port in tcpPorts is used
    - path: "/server-info"
    envDatabase: false
  db-vcs:
    type: task
    pullPolicy: IfNotPresent
    envDatabase: true
    maxRetrys: 1
    env_raw:
      TZ: UTC
