ARG DOCKER_HUB_USERNAME
ARG BUILD_TAG
FROM ${DOCKER_HUB_USERNAME}/sqitch:${BUILD_TAG}-test

COPY sqitch .
COPY waiting_for_db.sh /waiting_for_db.sh

CMD /waiting_for_db.sh && sqitch deploy --verify db:pg://${DB_USERNAME}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}
