{{- range $app, $appConfig := .Values.appsConfig }}
{{- $imageTag := default $appConfig.imageTag $.Values.defaultConfig.imageTag }}
{{- $replicas := default $appConfig.replicas $.Values.defaultConfig.replicas }}
{{- $pullPolicy := default $appConfig.pullPolicy $.Values.defaultConfig.pullPolicy }}
{{- $tcpPorts := default $appConfig.tcpPorts $.Values.defaultConfig.tcpPorts }}
{{- $udpPorts := default $appConfig.udpPorts $.Values.defaultConfig.udpPorts }}
{{- $chart := list $.Chart.Name $.Chart.Version | join "-" | replace "+" "_" | trunc 63 | trimSuffix "-" }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ list $.Release.Name $app | join "-" }}
  labels:
    app: {{ $app }}
    chart: {{ $chart }}
    release: {{ $.Release.Name }}
    build: {{ $imageTag }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app: {{ $app }}
      chart: {{ $chart }}
      release: {{ $.Release.Name }}
      build: {{ $imageTag }}
  template:
    metadata:
      labels:
        app: {{ $app }}
        chart: {{ $chart }}
        release: {{ $.Release.Name }}
        build: {{ $imageTag }}
    spec:
      containers:
        - name: {{ $app }}
          image: {{ list $app $imageTag | join ":" | quote }}
          imagePullPolicy: {{ $pullPolicy }}
          ports:
          {{- range $i, $tcpPort := $tcpPorts }}
            - containerPort: {{ $tcpPort }}
              protocol: TCP
          {{- end }}
          {{- range $i, $udpPort := $udpPorts }}
            - containerPort: {{ $udpPort }}
              protocol: UDP
          {{- end }}
---
{{- end }}