{{- range $app, $appConfig := .Values.appsConfig }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ list $.Release.Name $app | join "-" }}
  labels:
    {{- include "Networking.App.Label" (list $app $appConfig $) | indent 4 }}
spec:
  replicas: {{ $appConfig.replicas }}
  selector:
    matchLabels:
      {{- include "Networking.App.Label" (list $app $appConfig $) | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "Networking.App.Label" (list $app $appConfig $) | indent 8 }}
    spec:
      containers:
        - name: {{ $app }}
          image:  {{ $.Values.docker_image_path -}} /
                  {{- list $app $appConfig.build | join ":" }}
                  {{- if $.Values.testing -}} -test {{- end }}
          imagePullPolicy: {{ $appConfig.pullPolicy }}
          {{- if or $appConfig.tcpPorts $appConfig.udpPorts }}
          ports:
            {{- range $i, $tcpPort := $appConfig.tcpPorts }}
            - containerPort: {{ $tcpPort }}
              protocol: TCP
            {{- end }}
            {{- range $i, $udpPort := $appConfig.udpPorts }}
            - containerPort: {{ $udpPort }}
              protocol: UDP
            {{- end }}
          {{- end }}
---
{{- end }}