{{- range $app, $appConfig := .Values.appsConfig }}
{{- $imageTag := include "GetConfig" (list $appConfig $.Values.defaultConfig "imageTag") }}
{{- $replicas := include "GetConfig" (list $appConfig $.Values.defaultConfig "replicas") }}
{{- $pullPolicy := include "GetConfig" (list $appConfig $.Values.defaultConfig "pullPolicy") }}
{{- $tcpPort := include "GetConfig" (list $appConfig $.Values.defaultConfig "tcpPort") }}
{{- $udpPort := include "GetConfig" (list $appConfig $.Values.defaultConfig "udpPort") }}
{{- $chart := list $.Chart.Name $.Chart.Version | join "-" | replace "+" "_" | trunc 63 | trimSuffix "-" }}
note:
  - {{ include "GetValue" (list $ (list "Values" "defaultConfig" "some_list" 1)) }}
  - {{ include "GetValue" (list $ (list "Values" "defaultConfig" "some_list" 2)) }}
  - {{ include "GetValue" (list $ (list "Values" "defaultConfig" "some_list" 2 "haha")) }}
  - {{ include "GetValue" (list $ "Values" "defaultConfig" "some_list" 2 "haha") }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ list $.Release.Name $app | join "-" }}
  labels:
    app: {{ $app }}
    chart: {{ $chart }}
    release: {{ $.Release.Name }}
    build: {{ $imageTag }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app: {{ $app }}
      chart: {{ $chart }}
      release: {{ $.Release.Name }}
      build: {{ $imageTag }}
  template:
    metadata:
      labels:
        app: {{ $app }}
        chart: {{ $chart }}
        release: {{ $.Release.Name }}
        build: {{ $imageTag }}
    spec:
      containers:
        - name: {{ $app }}
          image: {{ list $app $imageTag | join ":" | quote }}
          imagePullPolicy: {{ $pullPolicy }}
          ports:
          {{- if $tcpPort }}
            - containerPort: {{ $tcpPort }}
              protocol: TCP
          {{- end }}
          {{- if $udpPort }}
            - containerPort: {{ $udpPort }}
              protocol: UDP
          {{- end }}
---
{{- end }}