{{- range $app, $config := .Values.appsConfig }}
---

{{- $imageTag := include "GetConfig" (list "imageTag" $config $) }}
{{- $replicas := include "GetConfig" (list "replicas" $config $) }}
{{- $pullPolicy := include "GetConfig" (list "pullPolicy" $config $) }}
{{- $tcpPort := include "GetConfig" (list "tcpPort" $config $) }}
{{- $udpPort := include "GetConfig" (list "udpPort" $config $) }}
{{- $chart := list $.Chart.Name $.Chart.Version | join "-" | replace "+" "_" | trunc 63 | trimSuffix "-" }}

note:
  - {{ include "GetValueByPath" (list $ (list "Values" "defaultConfig" "some_list" 1)) }}
  - {{ include "GetValueByPath" (list $ (list "Values" "defaultConfig" "some_list" 2)) }}
  - {{ include "GetValueByPath" (list $ (list "Values" "defaultConfig" "some_list" 2 "haha")) }}
  - {{ include "GetValue" (list $ "Values" "defaultConfig" "some_list" 2 "haha") }}
  - {{ kindOf $.Values.defaultConfig }}
  - {{ kindOf $.Values.defaultConfig.some_list }}
  - {{ kindOf "xxx" }}
  - {{ kindOf 1 }}
  - {{ kindOf nil }}
  - {{ typeOf $.Values.defaultConfig }}
  - {{ typeOf $.Values.defaultConfig.some_list }}
  - {{ typeOf "xxx" }}
  - {{ typeOf 1 }}
  - {{ typeOf nil }}
  - {{ kindIs "slice" "sss" | toJson }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ list $.Release.Name $app | join "-" }}
  labels:
    app: {{ $app }}
    chart: {{ $chart }}
    release: {{ $.Release.Name }}
    build: {{ $imageTag }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app: {{ $app }}
      chart: {{ $chart }}
      release: {{ $.Release.Name }}
      build: {{ $imageTag }}
  template:
    metadata:
      labels:
        app: {{ $app }}
        chart: {{ $chart }}
        release: {{ $.Release.Name }}
        build: {{ $imageTag }}
    spec:
      containers:
        - name: {{ $app }}
          image: {{ list $app $imageTag | join ":" | quote }}
          imagePullPolicy: {{ $pullPolicy }}
          ports:
          {{- if $tcpPort }}
            - containerPort: {{ $tcpPort }}
              protocol: TCP
          {{- end }}
          {{- if $udpPort }}
            - containerPort: {{ $udpPort }}
              protocol: UDP
          {{- end }}
{{- end }}