{{- range $app, $appConfig := .Values.appConfigs }}
{{- if eq (default "unknown" $appConfig.type) "service" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "Networking.App.DNSName" (list $app $) }}
  labels:
    {{- include "Networking.App.Label" (list $app $) | indent 4 }}
spec:
  replicas: {{ $appConfig.replicas }}
  selector:
    matchLabels:
      {{- include "Networking.App.Label" (list $app $) | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "Networking.App.Label" (list $app $) | indent 8 }}
    spec:
      {{- include "Networking.App.Volumes" (list $app $) | indent 6 }}
      {{- include "Networking.App.initContainers" (list $app $) | indent 6 }}
      containers:
        - name: {{ include "Networking.App.DNSName" (list $app $) }}
          image:  {{ $.Values.dockerRegistry -}} /
                  {{- list $app $.Values.buildTag | join ":" }}
                  {{- if $.Values.testing -}} -test {{- end }}
          imagePullPolicy: {{ $appConfig.pullPolicy }}
          {{- if or $appConfig.tcpPorts $appConfig.udpPorts }}
          ports:
            {{- range $i, $tcpPort := $appConfig.tcpPorts }}
            - containerPort: {{ $tcpPort }}
              protocol: TCP
            {{- end }}
            {{- range $i, $udpPort := $appConfig.udpPorts }}
            - containerPort: {{ $udpPort }}
              protocol: UDP
            {{- end }}
          {{- end }}
          {{- include "Networking.App.EnvSection" (list $app $) | indent 10 }}
          {{- include "Networking.App.VolumeMounts" (list $app $) | indent 10 }}
---
{{- end }}
{{- end }}