{{- range $app, $config := .Values.appsConfig }}
---
{{- $imageTag := $config.imageTag | default $.Values.defaultConfig.imageTag }}
{{- $replicas := $config.replicas | default $.Values.defaultConfig.replicas }}
{{- $pullPolicy := $config.pullPolicy | default $.Values.defaultConfig.pullPolicy }}
{{- $tcpPorts := $config.tcpPorts | default $.Values.defaultConfig.tcpPorts }}
{{- $udpPorts := $config.udpPorts | default $.Values.defaultConfig.udpPorts }}
{{- $chart := list $.Chart.Name $.Chart.Version | join "-" | replace "+" "_" | trunc 63 | trimSuffix "-" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ list $.Release.Name $app | join "-" }}
  labels:
    app: {{ $app }}
    chart: {{ $chart }}
    release: {{ $.Release.Name }}
    build: {{ $imageTag }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app: {{ $app }}
      chart: {{ $chart }}
      release: {{ $.Release.Name }}
      build: {{ $imageTag }}
  template:
    metadata:
      labels:
        app: {{ $app }}
        chart: {{ $chart }}
        release: {{ $.Release.Name }}
        build: {{ $imageTag }}
    spec:
      containers:
        - name: {{ $app }}
          image: {{ list $app $imageTag | join ":" | quote }}
          imagePullPolicy: {{ $pullPolicy }}
          ports:
          {{- range $i, $port := $tcpPorts }}
            - containerPort: {{ $port }}
              protocol: TCP
          {{- end }}
          {{- range $i, $port := $udpPorts }}
            - containerPort: {{ $port }}
              protocol: UDP
          {{- end }}
{{- end }}