apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: {{ list .Chart.Name .Chart.Version | join "-" | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    release: {{ .Release.Name }}
    testing: {{ .Values.testing | quote }}
  {{- if .Values.testing }}
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  {{- end }}

spec:
  {{- if not .Values.testing }}
  tls:
  - secretName: {{ .Values.tlsSecret }}
  {{- end }}
  rules:
  - http:
      paths:
      {{- range $app, $appConfig := .Values.appsConfig }}
        {{- if $appConfig.ingress -}}
          {{- with $ }}
            {{- range $i, $ingressConfig:= $appConfig.ingress }}
      - path: {{ $ingressConfig.path | quote }}
        backend:
          serviceName: {{ list $.Release.Name $app | join "-" }}
          servicePort: {{ $ingressConfig.port | default (index $appConfig.tcpPorts 0) }}
            {{ end -}}
          {{- end -}}
        {{- end -}}
      {{- end }}
