apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: {{ list .Chart.Name .Chart.Version | join "-" | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    release: {{ .Release.Name }}
    testing: {{ .Values.testing | quote }}
  annotations:
    kubernetes.io/ingress.class: nginx
    # external-dns.alpha.kubernetes.io/ttl: "60"  # bug: https://github.com/kubernetes-incubator/external-dns/issues/467
  {{- if .Values.testing }}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  {{- else }}
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  {{- end }}

spec:
  {{- if not .Values.testing }}
  tls:
  - secretName: {{ .Values.tlsSecret }}
  {{- end }}
  rules:
  {{- range $i, $host := .Values.hosts }}
  - http:
      paths:
      {{- range $app, $appConfig := $.Values.appConfigs }}
        {{- if $appConfig.ingress -}}
          {{- with $ }}
            {{- range $i, $ingressConfig:= $appConfig.ingress }}
      - path: {{ $ingressConfig.path | quote }}
        backend:
          serviceName: {{ include "Networking.App.DNSName" (list $app $) }}
          servicePort: {{ $ingressConfig.port | default (index $appConfig.tcpPorts 0) }}
            {{ end -}}
          {{- end -}}
        {{- end -}}
      {{- end }}
    {{- if ne $host "*" }}
    host: {{ $host | quote }}
    {{- end }}
  {{ end -}}