apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: default-issuer    # FIXME hard coded name
  labels:
    chart: {{ list .Chart.Name .Chart.Version | join "-" | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    release: {{ .Release.Name }}
    testing: {{ .Values.testing | quote }}
spec:
  acme:
    {{- if .Values.testing }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    {{- else }}
    server: https://acme-v02.api.letsencrypt.org/directory
    {{- end }}
    email: {{ .Values.ACME.email | quote }}
    privateKeySecretRef:
      name: {{ .Values.tlsSecret }}
    dns01:
      providers:
      - name: default-dns01-provider  # FIXME hard coded name
        clouddns:
          project: {{ .Values.ACME.dns.project }}
          serviceAccountSecretRef:
            name: {{ .Values.ACME.dns.secret }}
            key: {{ .Values.ACME.dns.secretKey }}
