{{- range $app, $appConfig := .Values.appConfigs }}
{{- if eq (default "unknown" $appConfig.type) "task" }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "Networking.App.DNSName" (list $app $) }}
  labels:
    {{- include "Networking.App.Label" (list $app $) | indent 4 }}
spec:
  activeDeadlineSeconds: {{ $appConfig.timeout | default 300 }}
  backoffLimit: {{ $appConfig.maxRetrys | default 6 }}
  template:
    metadata:
    labels:
      {{- include "Networking.App.Label" (list $app $) | indent 8 }}
    spec:
      restartPolicy: Never
      containers:
        - name: {{ include "Networking.App.DNSName" (list $app $) }}
          image:  {{ $.Values.dockerRegistry -}}
                  / {{- list $app $.Values.buildTag | join ":" }}
                  {{- if $.Values.testing -}} -test {{- end }}
          imagePullPolicy: {{ $appConfig.pullPolicy }}
          env:
          {{- if $.Values.testing }}
          - name: {{ include "Networking.App.EnvName" (list "TESTING" $appConfig) }}
            value: {{ $.Values.testing | quote }}
          {{- end }}
          {{- if $appConfig.databaseEnabled }}
          {{- if $.Values.testing }}
          - name: {{ include "Networking.App.EnvName" (list "DB_HOST" $appConfig) }}
            value: {{ list $.Release.Name (default "postgresTesting" $.Values.postgresTesting.nameOverride) | join "-" }}
          - name: {{ include "Networking.App.EnvName" (list "DB_PORT" $appConfig) }}
            value: {{ $.Values.postgresTesting.service.port | quote }}
          {{- else }}
          - name: {{ include "Networking.App.EnvName" (list "DB_HOST" $appConfig) }}
            value: {{ list $.Release.Name "postgres" | join "-" }}
          - name: {{ include "Networking.App.EnvName" (list "DB_PORT" $appConfig) }}
            value: {{ (index $.Values.postgres.cloudsql.instances 0).port | quote }}
          {{- end }}
          - name: {{ include "Networking.App.EnvName" (list "DB_USERNAME" $appConfig) }}
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.databaseSecret }}
                key: username
          - name: {{ include "Networking.App.EnvName" (list "DB_PASSWORD" $appConfig) }}
            valueFrom:
              secretKeyRef:
                name: {{ $.Values.databaseSecret }}
                key: password
          {{- end }}
          {{- if $appConfig.env }}
          {{- range $key, $val := $appConfig.env }}
          - name: {{ $key | quote }}
            value: {{ $val | quote }}
          {{- end }}
          {{- end }}
---
{{- end }}
{{- end }}