{{- if .Values.testing }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.databaseSecret }}
type: Opaque
data:
  username: {{ .Values.postgresTesting.postgresUser | b64enc }}
  password: {{ .Values.postgresTesting.postgresPassword | b64enc }}
{{- end }}