# Template Dockerfile for All Sanic Based Testing Apps
ARG DOCKER_REGISTRY
ARG BUILD_TAG
FROM ${DOCKER_REGISTRY}/sanic:${BUILD_TAG}-test

# Remove files used by from sanic testing
RUN rm -rf blueprint.py orm.py requirements.txt requirements-test.txt tests

# Add everything of the app
COPY blueprint.py orm.py requirements.txt requirements-test.txt ./
COPY tests tests
COPY views.py ./

# Install dependencies, no cleanup
RUN pip install -r requirements.txt -r requirements-test.txt